export type ContextEntryCategory =
  | "terminology"
  | "user_language"
  | "buyer_question"
  | "pain_point"
  | "use_case"
  | "install_constraint"
  | "device_pattern"
  | "specification"
  | "trend"
  | "competitor"
  | "regulation"
  | "ai_signal";

export type ContextEntrySourceType = "web" | "reddit" | "youtube" | "manual";

export interface ContextEnrichmentEntry {
  verticalSlug: string;
  category: ContextEntryCategory;
  content: string;
  sourceType?: ContextEntrySourceType;
  sourceUrl?: string;
  confidence?: number;
}

const SOURCE = {
  iboltMarine: "https://iboltmounts.com/collections/marine",
  ramFishFinder: "https://rammount.com/pages/kayak-fishfinder-mounts",
  yakAttackFishFinder: "https://www.yakattack.us/fish-finder-mounts/",
  lowranceKayak: "https://www.lowrance.com/lowrance/type/kayak-fishing/",
  kayakReddit: "https://www.reddit.com/r/kayakfishing/",
  forkliftOsha: "https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.178",
  zebraForkliftScanning: "https://www.zebra.com/us/en/resources/case-studies/forklift-mounted-pallet-scanning.html",
  iboltForklift: "https://iboltmounts.com/collections/forklift",
  forkliftReddit: "https://www.reddit.com/r/sysadmin/comments/7puxw5/windows_tablets_for_fork_lifts/",
  fmcsaEld: "https://www.fmcsa.dot.gov/hours-service/elds/faqs",
  iboltFleet: "https://iboltmounts.com/collections/fleet-heavy-duty-eld-mandate-mounts",
  proclipTruck: "https://www.proclipusa.com/collections/windshield-mounts",
  truckersReddit: "https://www.reddit.com/r/Truckers/",
  doorDashTablet: "https://help.doordash.com/merchants/s/article/Using-your-Tablet?language=en_US",
  uberEatsOrders: "https://merchants.ubereats.com/us/en/technology/orders/",
  squareStand: "https://squareup.com/us/en/hardware/stand",
  iboltPos: "https://iboltmounts.com/collections/point-of-sale",
  ghostKitchenReddit: "https://www.reddit.com/r/restaurateur/",
  appleVibration: "https://support.apple.com/en-us/102175",
  garminTread: "https://www.garmin.com/en-US/p/732617",
  ramPowersports: "https://rammount.com/pages/motorcycle-phone-mounts",
  iboltOffroad: "https://iboltmounts.com/collections/off-road",
  mtbReddit: "https://www.reddit.com/r/MTB/",
  iboltStreaming: "https://iboltmounts.com/collections/social-media-live-streaming-mounts",
  obsReddit: "https://www.reddit.com/r/obs/",
  videographyReddit: "https://www.reddit.com/r/videography/",
  iboltAgriculture: "https://iboltmounts.com/collections/agriculture",
  iboltTractor: "https://iboltmounts.com/collections/tractor",
  newAgTalkIpad: "https://talk.newagtalk.com/forums/thread-view.asp?DisplayType=flat&setCookie=1&tid=699122",
  farmingGpsReddit: "https://www.reddit.com/r/farming/comments/12s3lih/gps_guidance_for_my_tractor/",
  iboltEducation: "https://iboltmounts.com/collections/education",
  iboltSchoolBus: "https://iboltmounts.com/blogs/news/best-tablet-mount-for-school-bus-and-transportation-fleets",
  zonarSchoolBus: "https://support.zonarsystems.net/hc/en-us/articles/360016659051-Tablet-Installation-Guidelines-for-School-Buses-by-State-and-Province",
  schoolBusReddit: "https://www.reddit.com/r/SchoolBusDrivers/comments/1n5hm0s/are_mounted_tablets_ever_utilized_on_school_buses/",
  teachersReddit: "https://www.reddit.com/r/Teachers/comments/1s6amzu/what_are_some_classroom_purchases_you_made_that/",
  iboltKitchen: "https://iboltmounts.com/collections/kitchen",
  iboltMagDock: "https://iboltmounts.com/products/ibolt-tabdock-magdock-heavy-duty-magnetic-mount-for-fridges-restaurants-automotive-workout-equipment",
  cookingReddit: "https://www.reddit.com/r/Cooking/",
  smartHomeReddit: "https://www.reddit.com/r/homeassistant/",
  iboltHeadrest: "https://iboltmounts.com/collections/headrest-mounts",
  iboltRoadTrip: "https://iboltmounts.com/blogs/news/best-nintendo-switch-headrest-mount-for-road-trips",
  roadTripReddit: "https://www.reddit.com/r/roadtrip/",
  familyTravelReddit: "https://www.reddit.com/r/TravelHacks/",
  iboltCycling: "https://iboltmounts.com/collections/bicycle-mounts",
  quadLockVibration: "https://www.quadlockcase.com/collections/vibration-dampener",
  trailforks: "https://www.trailforks.com/apps/map/",
  ampsPlateIbolt: "https://iboltmounts.com/products/17mm-garmin-compatible-amps-plate-21145",
  ampsExplainer: "https://arkon.com/blogs/how-to-videos/amps-mounting-system-explained",
  mountDepotAmps: "https://www.themountdepot.com/hole-pattern/4-hole-amps-1-181-x-1-496-2-hole-amps-1-912-mic-mounting-plate-hole-pattern/",
  vesaMisD: "https://www.vesa-standard.com/vesa-mis-d.html",
  iboltBallAdapters: "https://iboltmounts.com/collections/1-5-inch-ball-adapters-and-mounts",
  iboltAccessibolt: "https://iboltmounts.com/products/ibolt-tabdock-accessibolt-universal-wheelchair-mobility-tablet-mount",
  iboltAccessiboltDock: "https://iboltmounts.com/products/ibolt-accessibolt-dock-n-lock-wheelchair-mobility-tablet-mount",
  iboltWheelchairGuide: "https://iboltmounts.com/blogs/news/best-wheelchair-tablet-mount-for-communication-devices",
  iboltVesaAmps: "https://iboltmounts.com/products/ibolt-38mm-1-5-inch-metal-circular-amps-pattern-to-vesa-75-x-75-vesa-100-x-100-dual-ball-mount",
};

export const CONTEXT_ENRICHMENT_RUN_ID_2026_06_22 = "category-bank-user-language-2026-06-22";

export const CONTEXT_ENRICHMENT_RUN_2026_06_22 = [
  {
    verticalSlug: "fishing-boating",
    category: "terminology",
    content: "Fishing buyers often call fish finders 'graphs,' 'FFs,' 'depth finders,' and 'chartplotters'; sonar language includes 2D, down imaging, side imaging, Livescope, Mega Live, and ActiveTarget.",
    sourceUrl: SOURCE.kayakReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "fishing-boating",
    category: "buyer_question",
    content: "Common buyer question: can a Garmin Striker, Lowrance Hook, or Humminbird Helix mount directly to a kayak track, or does it need an AMPS plate, ball adapter, or gimbal bracket?",
    sourceUrl: SOURCE.lowranceKayak,
  },
  {
    verticalSlug: "fishing-boating",
    category: "install_constraint",
    content: "Kayak fish finder mounts need to preserve paddle stroke, pedal-drive clearance, rod-holder access, cockpit space, and transducer-arm movement.",
    sourceUrl: SOURCE.yakAttackFishFinder,
  },
  {
    verticalSlug: "fishing-boating",
    category: "pain_point",
    content: "Real fishing complaints center on rough-water wobble, ball slippage, transducer movement, and mounts that loosen in chop or motor vibration.",
    sourceUrl: SOURCE.ramFishFinder,
  },
  {
    verticalSlug: "fishing-boating",
    category: "device_pattern",
    content: "Four- to five-inch fish finder screens fit budget kayak setups; seven- to nine-inch screens are common for split-screen sonar; nine- to twelve-inch displays need shorter arms, larger balls, and stronger bases.",
    sourceUrl: SOURCE.ramFishFinder,
  },
  {
    verticalSlug: "fishing-boating",
    category: "specification",
    content: "Marine electronics content should connect AMPS plates, 25mm or 38mm ball systems, drill bases, and rail or handlebar clamps to fish finder and chartplotter fit.",
    sourceUrl: SOURCE.iboltMarine,
  },
  {
    verticalSlug: "fishing-boating",
    category: "use_case",
    content: "Inshore and saltwater users want fish finder visibility for depth, bait balls, channel edges, sandbars, obstacles, waypoints, and navigation back to launch.",
    sourceUrl: SOURCE.lowranceKayak,
  },
  {
    verticalSlug: "fishing-boating",
    category: "pain_point",
    content: "Transducer mounting creates tradeoffs: in-hull installs protect the transducer but can lose temperature readings; external arms preserve readings but can snag on weeds, docks, or shallow water.",
    sourceUrl: SOURCE.yakAttackFishFinder,
  },
  {
    verticalSlug: "fishing-boating",
    category: "trend",
    content: "Forward-facing sonar and larger displays are pushing kayak and small-boat buyers toward stronger tracks, shorter arms, larger ball sizes, and better battery planning.",
    sourceUrl: SOURCE.lowranceKayak,
  },
  {
    verticalSlug: "fishing-boating",
    category: "competitor",
    content: "RAM and YakAttack dominate many kayak fish finder discussions; comparison content should address RAM ball adjustability, YakAttack LockNLoad-style security, and iBOLT AMPS/ball compatibility.",
    sourceUrl: SOURCE.yakAttackFishFinder,
  },

  {
    verticalSlug: "forklifts-warehousing",
    category: "install_constraint",
    content: "Forklift tablet and scanner mounts must stay out of the operator's sightlines to forks, pallet corners, pedestrians, racking, mast, mirrors, controls, and warning lights.",
    sourceUrl: SOURCE.forkliftOsha,
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "user_language",
    content: "Warehouse teams describe scanners as 'rattling around in a cup holder,' 'dangling from a lanyard,' or 'sitting in the operator's lap' when there is no dedicated scanner holder.",
    sourceUrl: SOURCE.forkliftReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "specification",
    content: "For forklift tablets and scanner holders, 38mm C-size and 57mm ball systems read as more credible than consumer-size phone mounts because vibration and device weight are higher.",
    sourceUrl: SOURCE.iboltForklift,
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "buyer_question",
    content: "Common buyer question: can one forklift mount hold both a WMS tablet and a Zebra, Honeywell, Symbol, or Datalogic barcode scanner without blocking visibility?",
    sourceUrl: SOURCE.zebraForkliftScanning,
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "use_case",
    content: "Forklift-mounted scanning is tied to pallet verification, misload reduction, faster loading, traceability, and live WMS or ERP updates.",
    sourceUrl: SOURCE.zebraForkliftScanning,
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "pain_point",
    content: "Warehouse mounts face constant vibration, dust, moisture, cold storage temperature swings, rack impacts, and repeated shift-change adjustments.",
    sourceUrl: SOURCE.iboltForklift,
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "install_constraint",
    content: "Clamp and pillar mounts are preferred for fixed high-vibration forklift installs; magnetic mounts only make sense on flat steel surfaces where load, movement, and safety policies allow them.",
    sourceUrl: SOURCE.iboltForklift,
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "device_pattern",
    content: "Forklift buyers separate software fit from hardware fit: the tablet may run WMS, ERP, RDP, or browser workflows, while the mount must fit the rugged case, scanner, power cable, and vehicle surface.",
    sourceUrl: SOURCE.forkliftReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "regulation",
    content: "Powered industrial truck content should say screens and scanners must not encourage use while moving, reduce clear view, or bypass the site's EHS rules.",
    sourceUrl: SOURCE.forkliftOsha,
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "buyer_question",
    content: "Common buyer question: is a magnetic, clamp, drill-base, overhead-guard, or seat-rail mount best for a forklift tablet in a warehouse?",
    sourceUrl: SOURCE.iboltForklift,
  },

  {
    verticalSlug: "trucking-fleet",
    category: "regulation",
    content: "FMCSA ELD guidance allows portable ELDs such as smartphones or wireless devices if they meet specs, are fixed during CMV operation, and are visible from the driver's normal seated position.",
    sourceUrl: SOURCE.fmcsaEld,
  },
  {
    verticalSlug: "trucking-fleet",
    category: "user_language",
    content: "Truck drivers ask for ELD and GPS screens 'close enough to glance at' without placing the tablet in the center of the windshield or blocking road view.",
    sourceUrl: SOURCE.truckersReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "trucking-fleet",
    category: "install_constraint",
    content: "Company drivers often cannot drill into dashboards, so no-drill suction, cup-holder, wedge, seat-rail, and gooseneck options matter.",
    sourceUrl: SOURCE.iboltFleet,
  },
  {
    verticalSlug: "trucking-fleet",
    category: "pain_point",
    content: "Fleet and delivery drivers complain about windshield suction mounts overheating phones during GPS-heavy shifts and falling off in summer heat.",
    sourceUrl: SOURCE.truckersReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "trucking-fleet",
    category: "specification",
    content: "Commercial ELD tablet content should mention locking cradles, AMPS plates, 38mm or 1.5-inch ball systems, hardwire or USB-C charging, and vibration-resistant arms.",
    sourceUrl: SOURCE.iboltFleet,
  },
  {
    verticalSlug: "trucking-fleet",
    category: "buyer_question",
    content: "Common buyer question: what is the best ELD tablet mount for a semi truck when the driver needs visibility, no-drill installation, and a tablet that stays put on rough roads?",
    sourceUrl: SOURCE.fmcsaEld,
  },
  {
    verticalSlug: "trucking-fleet",
    category: "use_case",
    content: "Delivery and last-mile drivers need fast one-hand docking for navigation, messaging, scanning, proof-of-delivery photos, route apps, and grocery substitution workflows.",
    sourceUrl: SOURCE.iboltFleet,
  },
  {
    verticalSlug: "trucking-fleet",
    category: "install_constraint",
    content: "Truck mount pages should address cable routing, charging clearance, vibration, gauges, vents, airbags, and whether the mount is shared across multiple drivers.",
    sourceUrl: SOURCE.proclipTruck,
  },
  {
    verticalSlug: "trucking-fleet",
    category: "device_pattern",
    content: "Fleet setups often combine an ELD tablet, phone, GPS unit, dash cam, or dispatch device, so content should help buyers avoid dashboard clutter and duplicated mounts.",
    sourceUrl: SOURCE.iboltFleet,
  },
  {
    verticalSlug: "trucking-fleet",
    category: "ai_signal",
    content: "For AI-answer visibility, ELD pages should explicitly answer 'where should an ELD be mounted,' 'is a phone allowed as an ELD,' and 'what does fixed and visible mean.'",
    sourceUrl: SOURCE.fmcsaEld,
  },

  {
    verticalSlug: "restaurants-food-delivery",
    category: "terminology",
    content: "Restaurant buyers use terms like DoorDash tablet, Uber Eats Orders, Grubhub tablet, merchant tablet, delivery app station, POS stand, KDS, expo line, pass, ghost kitchen, and multi-app setup.",
    sourceUrl: SOURCE.doorDashTablet,
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "pain_point",
    content: "Restaurant operators describe the problem as 'tablet clutter' when DoorDash, Uber Eats, Grubhub, and POS devices compete for the same counter space during rush.",
    sourceUrl: SOURCE.ghostKitchenReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "use_case",
    content: "QSRs and ghost kitchens need fast visual access to multiple app tablets so staff can accept orders, spot alerts, adjust prep times, and avoid missed tickets.",
    sourceUrl: SOURCE.uberEatsOrders,
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "install_constraint",
    content: "Wall mounts make sense near the kitchen pass or expo line when teams need eye-level screens and zero counter footprint.",
    sourceUrl: SOURCE.iboltPos,
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "install_constraint",
    content: "Clamp mounts fit restaurants that cannot drill into stainless counters, leased spaces, temporary stations, pop-ups, or food truck service windows.",
    sourceUrl: SOURCE.iboltPos,
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "pain_point",
    content: "Kitchen tablets should not sit near ovens, fryers, ranges, greasy prep, or wet dish areas; mounting should lift devices away from spills, heat, and splatter.",
    sourceUrl: SOURCE.iboltPos,
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "device_pattern",
    content: "Restaurant setups often mix app-provided iPads, Android tablets, Fire tablets, POS displays, and customer-facing checkout screens, so universal 7- to 11-inch fit matters.",
    sourceUrl: SOURCE.squareStand,
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "buyer_question",
    content: "Common buyer question: what mount holds three, four, or five delivery app tablets for DoorDash, Uber Eats, Grubhub, and a POS system?",
    sourceUrl: SOURCE.iboltPos,
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "trend",
    content: "Direct POS integrations can reduce tablet count, but restaurants still keep merchant tablets for alerts, fallback, support, and multi-platform order management.",
    sourceUrl: SOURCE.uberEatsOrders,
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "use_case",
    content: "Food trucks need compact, secure tablet and POS mounts that tolerate motion, window service, limited depth, heat, and quick device removal after service.",
    sourceUrl: SOURCE.iboltPos,
  },

  {
    verticalSlug: "offroading-jeep",
    category: "terminology",
    content: "Off-road buyers search with roll bar, roll cage, tube frame, SxS, UTV, ATV, overlanding, GPX, Gaia GPS, onX Offroad, Garmin Tread, B-size, C-size, AMPS, and vibration dampener.",
    sourceUrl: SOURCE.garminTread,
  },
  {
    verticalSlug: "offroading-jeep",
    category: "pain_point",
    content: "Powersports and motorcycle buyers worry that bar-mounted phones can damage optical image stabilization or autofocus; content should mention vibration dampening and when a dedicated GPS or action camera is smarter.",
    sourceUrl: SOURCE.appleVibration,
  },
  {
    verticalSlug: "offroading-jeep",
    category: "install_constraint",
    content: "UTV and ATV shoppers search by roll-cage or tube diameter, so content should tell them to measure tube size and match the clamp range before buying.",
    sourceUrl: SOURCE.iboltOffroad,
  },
  {
    verticalSlug: "offroading-jeep",
    category: "device_pattern",
    content: "Jeep and overlanding setups often use Gaia GPS, onX, offline maps, tablets, Garmin Tread devices, phones, radios, and action cameras at the same time.",
    sourceUrl: SOURCE.garminTread,
  },
  {
    verticalSlug: "offroading-jeep",
    category: "specification",
    content: "A 1.5-inch or 38mm C-size ball is a better fit for iPads, larger Garmin units, and heavy off-road tablet setups when wobble is a concern; 1-inch balls fit lighter devices.",
    sourceUrl: SOURCE.iboltBallAdapters,
  },
  {
    verticalSlug: "offroading-jeep",
    category: "user_language",
    content: "Trail users say they are tired of stopping at every fork to pull out a phone, but also worry a phone on the bars will shake loose or damage the camera.",
    sourceUrl: SOURCE.mtbReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "offroading-jeep",
    category: "competitor",
    content: "RAM, Quad Lock, and Garmin are common comparison points: RAM for rugged modularity, Quad Lock for phone locking and dampening, Garmin for dedicated rugged navigation.",
    sourceUrl: SOURCE.ramPowersports,
  },
  {
    verticalSlug: "offroading-jeep",
    category: "use_case",
    content: "Action camera mounts on roll bars, handlebars, posts, rails, and cages support POV footage, dash-cam style footage, rear-facing shots, and alternate trail angles.",
    sourceUrl: SOURCE.iboltOffroad,
  },
  {
    verticalSlug: "offroading-jeep",
    category: "pain_point",
    content: "Off-road mounts need to address mud, dust, rain, gloves, washboard roads, water crossings, and fast removal when the vehicle is parked or washed.",
    sourceUrl: SOURCE.iboltOffroad,
  },
  {
    verticalSlug: "offroading-jeep",
    category: "ai_signal",
    content: "Avoid promising vibration elimination; explain how mount location, arm length, device weight, ball size, clamp quality, and dampening all affect trail stability.",
    sourceUrl: SOURCE.appleVibration,
  },

  {
    verticalSlug: "education-schools",
    category: "use_case",
    content: "School transportation teams use mounted tablets for route navigation, stop lists, student ridership, pre-trip workflows, GPS, and dispatch communication.",
    sourceUrl: SOURCE.iboltSchoolBus,
  },
  {
    verticalSlug: "education-schools",
    category: "install_constraint",
    content: "School bus tablet mounting should lead with driver sightline, mirror visibility, gauges, controls, driver entry path, cable routing, vibration, and secure docking.",
    sourceUrl: SOURCE.zonarSchoolBus,
  },
  {
    verticalSlug: "education-schools",
    category: "regulation",
    content: "Some school bus policies require tablets to be removable, firmly secured, safely located, and capable of going dark or silent while the bus is moving.",
    sourceUrl: SOURCE.zonarSchoolBus,
  },
  {
    verticalSlug: "education-schools",
    category: "user_language",
    content: "Bus driver language includes 'mounted tablets,' 'directions,' 'route info,' 'every kid loaded to each stop,' and frustration when car-style routing suggests unsafe bus maneuvers.",
    sourceUrl: SOURCE.schoolBusReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "education-schools",
    category: "buyer_question",
    content: "Common buyer question: where can a school bus tablet be mounted without blocking mirrors, gauges, controls, driver entry, airbags, or road view?",
    sourceUrl: SOURCE.zonarSchoolBus,
  },
  {
    verticalSlug: "education-schools",
    category: "use_case",
    content: "Teachers use iPads with Apple TV, Apple Pencil, Goodnotes, and document-camera workflows for instruction, worksheet scanning, handwriting demos, and recorded lessons.",
    sourceUrl: SOURCE.teachersReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "education-schools",
    category: "pain_point",
    content: "Classroom stands need to avoid wobble during handwriting, scanning, recording, and student interaction; locking stands matter in shared rooms, libraries, and check-in desks.",
    sourceUrl: SOURCE.iboltEducation,
  },
  {
    verticalSlug: "education-schools",
    category: "device_pattern",
    content: "Education content should include iPad, iPad Air, iPad mini, Samsung Galaxy Tab, Chromebook-adjacent tablets, Fire tablets, Surface Go, and rugged cases.",
    sourceUrl: SOURCE.iboltEducation,
  },

  {
    verticalSlug: "content-creation-streaming",
    category: "terminology",
    content: "Creator buyers use terms like phone stand for live streaming, table camera mount, overhead camera rig, top-down shot, flat lay, desk clamp, C-clamp, boom arm, ball head, 1/4-20, cold shoe, OBS, and ATEM.",
    sourceUrl: SOURCE.videographyReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "content-creation-streaming",
    category: "buyer_question",
    content: "Common buyer question: what phone stand or table camera mount gives a stable overhead top-down shot for cooking, drawing, unboxing, repairs, or live selling?",
    sourceUrl: SOURCE.obsReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "content-creation-streaming",
    category: "pain_point",
    content: "Creators often learn that flexible goosenecks and light clamp arms shake when the desk is touched; overhead video stability usually requires a rigid arm, stronger clamp, wall mount, ceiling mount, or heavier base.",
    sourceUrl: SOURCE.videographyReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "content-creation-streaming",
    category: "specification",
    content: "The 1/4-20 screw thread is the key compatibility standard for cameras, phone clamps, webcams, lights, mics, mini projectors, ball heads, and adapter plates.",
    sourceUrl: SOURCE.iboltStreaming,
  },
  {
    verticalSlug: "content-creation-streaming",
    category: "install_constraint",
    content: "Streaming mount content should ask about tabletop thickness, glass edges, desk lip shape, wall clearance, monitor placement, lighting, cable strain, and whether drilling is allowed.",
    sourceUrl: SOURCE.iboltStreaming,
  },
  {
    verticalSlug: "content-creation-streaming",
    category: "device_pattern",
    content: "Many creators start with one phone, then add a second phone, tablet monitor, action camera, webcam, light, or mic; modular bars and adapters reduce stand clutter.",
    sourceUrl: SOURCE.iboltStreaming,
  },
  {
    verticalSlug: "content-creation-streaming",
    category: "use_case",
    content: "Product demos and live selling benefit from repeatable framing, so pages should explain how a fixed mount improves consistent shots compared with a handheld phone or tripod.",
    sourceUrl: SOURCE.iboltStreaming,
  },
  {
    verticalSlug: "content-creation-streaming",
    category: "install_constraint",
    content: "Cooking and kitchen creators need camera mounts that clear bowls, cutting boards, steam, splatter, and cabinet doors while keeping the phone reachable for controls.",
    sourceUrl: SOURCE.cookingReddit,
    sourceType: "reddit",
  },

  {
    verticalSlug: "agriculture-farming",
    category: "buyer_question",
    content: "Common buyer question: what is the best tablet mount for a tractor cab when the operator needs GPS guidance, maps, work orders, and charging without blocking OEM monitors?",
    sourceUrl: SOURCE.newAgTalkIpad,
  },
  {
    verticalSlug: "agriculture-farming",
    category: "install_constraint",
    content: "Tractor cab installs need to account for curved glass, monitor placement, vibration, rugged tablet cases, cable routing, seasonal equipment swaps, and limited flat surfaces.",
    sourceUrl: SOURCE.newAgTalkIpad,
  },
  {
    verticalSlug: "agriculture-farming",
    category: "user_language",
    content: "Farmers ask about 'GPS guidance,' 'straight line,' 'overlap,' 'missed spots,' and 'I don't need auto steer,' which signals practical guidance workflows rather than only full precision-ag systems.",
    sourceUrl: SOURCE.farmingGpsReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "agriculture-farming",
    category: "pain_point",
    content: "Curved cab glass weakens suction mounts, long arms amplify bounce, dust loosens cheap plastic parts, and thick rugged cases can make normal tablet holders too shallow.",
    sourceUrl: SOURCE.newAgTalkIpad,
  },
  {
    verticalSlug: "agriculture-farming",
    category: "specification",
    content: "Precision-ag tablet pages should mention AMPS, VESA, 25mm and 38mm ball sizes, drill bases, suction bases, clamp mounts, ROPS bars, monitor rails, and backing plates.",
    sourceUrl: SOURCE.iboltAgriculture,
  },
  {
    verticalSlug: "agriculture-farming",
    category: "use_case",
    content: "Farm UTV and sprayer mounts support mapping, fence checks, livestock tasks, spray records, work orders, camera feeds, and moving the same tablet between machines.",
    sourceUrl: SOURCE.iboltAgriculture,
  },
  {
    verticalSlug: "agriculture-farming",
    category: "device_pattern",
    content: "Agriculture device examples should include iPad, iPad Pro, Samsung Galaxy Tab Active, rugged Android tablets, Amazon Fire, Lenovo Tab, Surface Go, and Google Pixel Tablet.",
    sourceUrl: SOURCE.iboltTractor,
  },
  {
    verticalSlug: "agriculture-farming",
    category: "ai_signal",
    content: "Agriculture content should answer surface-first decisions: suction on flat cab glass, drill base for permanent installs, clamp for bars/posts, and shorter arms for rough fields.",
    sourceUrl: SOURCE.iboltAgriculture,
  },

  {
    verticalSlug: "kitchen-home",
    category: "terminology",
    content: "Kitchen and home buyers search for recipe tablet stand, kitchen iPad mount, under-cabinet tablet mount, refrigerator tablet mount, magnetic tablet mount, smart home dashboard, and overhead cooking phone mount.",
    sourceUrl: SOURCE.iboltKitchen,
  },
  {
    verticalSlug: "kitchen-home",
    category: "buyer_question",
    content: "Common buyer question: what tablet mount keeps a recipe screen visible while cooking without taking up counter space or getting splattered?",
    sourceUrl: SOURCE.cookingReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "kitchen-home",
    category: "pain_point",
    content: "Kitchen device mounts need to avoid grease, steam, flour, splatter, wet hands, hot burners, sink areas, and cords crossing prep surfaces.",
    sourceUrl: SOURCE.iboltKitchen,
  },
  {
    verticalSlug: "kitchen-home",
    category: "install_constraint",
    content: "Magnetic mounts can work on refrigerators and other magnetic metal surfaces, but buyers need to confirm the surface is actually magnetic, flat, clean, and away from heat.",
    sourceUrl: SOURCE.iboltMagDock,
  },
  {
    verticalSlug: "kitchen-home",
    category: "use_case",
    content: "Home dashboards mount tablets for calendars, recipes, timers, smart home controls, grocery lists, video calls, security camera views, and family command centers.",
    sourceUrl: SOURCE.smartHomeReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "kitchen-home",
    category: "install_constraint",
    content: "Under-cabinet and wall-mounted kitchen setups must clear cabinet doors, appliance handles, charging cables, backsplash tile, and typical cooking reach.",
    sourceUrl: SOURCE.iboltKitchen,
  },
  {
    verticalSlug: "kitchen-home",
    category: "device_pattern",
    content: "Kitchen mounts should cover iPads, Fire tablets, Samsung Galaxy Tabs, Lenovo Tabs, phones, small cameras, and tablets in washable or rugged cases.",
    sourceUrl: SOURCE.iboltKitchen,
  },
  {
    verticalSlug: "kitchen-home",
    category: "use_case",
    content: "Overhead cooking video setups need top-down framing over cutting boards and mixing bowls while keeping lights, steam, and charging cables out of the shot.",
    sourceUrl: SOURCE.iboltStreaming,
  },

  {
    verticalSlug: "road-trips-travel",
    category: "terminology",
    content: "Road-trip buyers search for headrest tablet mount, backseat tablet holder, Nintendo Switch headrest mount, cup-holder tablet mount, car tablet mount, RV tablet mount, passenger iPad mount, and no-drill travel mount.",
    sourceUrl: SOURCE.iboltHeadrest,
  },
  {
    verticalSlug: "road-trips-travel",
    category: "buyer_question",
    content: "Common buyer question: what is the best headrest tablet mount for kids on long road trips that also works with a Nintendo Switch, iPad, or Fire tablet?",
    sourceUrl: SOURCE.iboltRoadTrip,
  },
  {
    verticalSlug: "road-trips-travel",
    category: "pain_point",
    content: "Family travel pain points include tablets falling during bumps, kids kicking screens, charging cables stretching across seats, cases not fitting holders, and mounts that are hard to remove in rental cars.",
    sourceUrl: SOURCE.roadTripReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "road-trips-travel",
    category: "install_constraint",
    content: "Rental cars, rideshares, and borrowed vehicles favor no-drill mounts such as headrest, cup-holder, suction, seat-rail, or clamp options that remove cleanly.",
    sourceUrl: SOURCE.iboltHeadrest,
  },
  {
    verticalSlug: "road-trips-travel",
    category: "use_case",
    content: "Backseat entertainment mounts support movies, games, video calls, offline downloads, navigation previews, Nintendo Switch play, and keeping kids from holding devices for hours.",
    sourceUrl: SOURCE.iboltRoadTrip,
  },
  {
    verticalSlug: "road-trips-travel",
    category: "device_pattern",
    content: "Road-trip mount pages should cover iPad, iPad mini, Fire HD, Samsung Tab, Nintendo Switch, phones, compact DVD-replacement screens, and tablets with bulky kid-proof cases.",
    sourceUrl: SOURCE.iboltRoadTrip,
  },
  {
    verticalSlug: "road-trips-travel",
    category: "install_constraint",
    content: "Travel setups need to consider seat movement, headrest post spacing, viewing angle, charging reach, passenger safety, airbag zones, and quick removal at stops.",
    sourceUrl: SOURCE.iboltHeadrest,
  },
  {
    verticalSlug: "road-trips-travel",
    category: "user_language",
    content: "Parents and travelers ask for mounts that 'keep the tablet off the floor,' 'stop the kids fighting over the screen,' and 'work in the rental car without tools.'",
    sourceUrl: SOURCE.familyTravelReddit,
    sourceType: "reddit",
  },

  {
    verticalSlug: "mountain-biking-cycling",
    category: "terminology",
    content: "Cycling buyers use Trailforks, GPX, bikepacking, e-bike, handlebar clamp, stem mount, Quad Lock, Garmin Edge, Wahoo, phone-on-bars, vibration dampener, and 1-inch ball language.",
    sourceUrl: SOURCE.trailforks,
  },
  {
    verticalSlug: "mountain-biking-cycling",
    category: "pain_point",
    content: "Mountain bikers worry that a phone on the bars can shake loose or damage the camera, while keeping the phone in a pack makes navigation slower at every trail fork.",
    sourceUrl: SOURCE.mtbReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "mountain-biking-cycling",
    category: "device_pattern",
    content: "Cyclists split between phone mounts for large navigation screens and dedicated Garmin/Wahoo computers for lighter, rugged, lower-risk trail data.",
    sourceUrl: SOURCE.quadLockVibration,
  },
  {
    verticalSlug: "mountain-biking-cycling",
    category: "buyer_question",
    content: "Common buyer question: should I put my phone on the bars for Trailforks or use a Garmin/Wahoo device to avoid camera vibration damage?",
    sourceUrl: SOURCE.appleVibration,
  },
  {
    verticalSlug: "mountain-biking-cycling",
    category: "install_constraint",
    content: "Bike mounts need to account for handlebar diameter, stem space, brake and shifter cables, gloves, rain, mud, crashes, and quick phone removal.",
    sourceUrl: SOURCE.iboltCycling,
  },
  {
    verticalSlug: "mountain-biking-cycling",
    category: "competitor",
    content: "Quad Lock is a common cycling comparison point because of its case-based locking system and optional vibration dampener; RAM is a comparison point for ball-and-arm modularity.",
    sourceUrl: SOURCE.quadLockVibration,
  },
  {
    verticalSlug: "mountain-biking-cycling",
    category: "use_case",
    content: "Bike and e-bike mounts support trail maps, delivery apps, fitness tracking, music controls, action camera framing, route recording, and bikepacking navigation.",
    sourceUrl: SOURCE.iboltCycling,
  },

  {
    verticalSlug: "general-mounting",
    category: "terminology",
    content: "General mounting buyers need plain explanations of AMPS plate, AMPS hole pattern, VESA 75x75, VESA 100x100, 17mm ball, 20mm ball, 25mm or 1-inch B-size ball, 38mm or 1.5-inch C-size ball, socket arm, and 1/4-20 screw mount.",
    sourceUrl: SOURCE.ampsExplainer,
  },
  {
    verticalSlug: "general-mounting",
    category: "specification",
    content: "The 4-hole AMPS pattern is commonly described as a rectangular four-hole layout around 30mm by 38mm; content should tell buyers to measure hole spacing instead of guessing by product photo.",
    sourceUrl: SOURCE.mountDepotAmps,
  },
  {
    verticalSlug: "general-mounting",
    category: "specification",
    content: "VESA MIS-D commonly uses 75x75mm or 100x100mm square hole patterns for monitors and smaller displays, which is different from AMPS even though both use four mounting holes.",
    sourceUrl: SOURCE.vesaMisD,
  },
  {
    verticalSlug: "general-mounting",
    category: "buyer_question",
    content: "Common buyer question: do I need 17mm, 20mm, 25mm, or 38mm ball size, and will my Garmin, phone clamp, tablet holder, camera, or monitor fit the same arm?",
    sourceUrl: SOURCE.ampsPlateIbolt,
  },
  {
    verticalSlug: "general-mounting",
    category: "device_pattern",
    content: "17mm ball mounts are commonly associated with Garmin-style GPS and lightweight holders; 25mm or 1-inch B-size balls fit many phone/tablet setups; 38mm or 1.5-inch C-size balls fit heavier tablets, monitors, and industrial use.",
    sourceUrl: SOURCE.iboltBallAdapters,
  },
  {
    verticalSlug: "general-mounting",
    category: "buyer_question",
    content: "Common buyer question: what is the difference between a phone clamp, clip-on phone mount, screw mount, ball-and-socket mount, and AMPS plate?",
    sourceUrl: SOURCE.ampsExplainer,
  },
  {
    verticalSlug: "general-mounting",
    category: "use_case",
    content: "Accessibility mounts support communication devices, AAC apps, entertainment, rehab chair use, wheelchair pole mounting, and tablet access during daily activities.",
    sourceUrl: SOURCE.iboltAccessibolt,
  },
  {
    verticalSlug: "general-mounting",
    category: "install_constraint",
    content: "Wheelchair tablet mounts need to be tested during real daily activities because a position that works for communication can interfere with eating, transfers, joystick access, tray use, or caregiver access.",
    sourceUrl: SOURCE.iboltWheelchairGuide,
  },
  {
    verticalSlug: "general-mounting",
    category: "device_pattern",
    content: "Accessibility content should include iPad, Samsung tablets, AAC communication apps, rehab chairs, mobility devices, wheelchair poles, and track systems.",
    sourceUrl: SOURCE.iboltAccessiboltDock,
  },
  {
    verticalSlug: "general-mounting",
    category: "use_case",
    content: "Retail, kiosk, cart, bed, and desk mounting pages should explain when locking tablet holders, VESA adapters, AMPS plates, drill bases, clamps, and articulating arms are the right fit.",
    sourceUrl: SOURCE.iboltVesaAmps,
  },
  {
    verticalSlug: "general-mounting",
    category: "ai_signal",
    content: "General mount guides should answer compatibility in steps: identify device thread or plate, measure hole pattern or ball size, choose base by surface, choose arm length by device weight and vibration.",
    sourceUrl: SOURCE.ampsPlateIbolt,
  },
  {
    verticalSlug: "fishing-boating",
    category: "buyer_question",
    content: "Real setup question: is a RAM ball strong enough for a seven-inch fish finder on a kayak, or should I use a shorter arm or heavier-duty AMPS mount?",
    sourceUrl: SOURCE.ramFishFinder,
  },
  {
    verticalSlug: "fishing-boating",
    category: "buyer_question",
    content: "Real setup question: should I drill a fish finder mount into my boat, clamp it to a rail, or use a track mount if I may move the screen later?",
    sourceUrl: SOURCE.yakAttackFishFinder,
  },
  {
    verticalSlug: "fishing-boating",
    category: "buyer_question",
    content: "Real setup question: where should the transducer and display go on a kayak so the screen is visible but the arm does not hit the paddle or pedal drive?",
    sourceUrl: SOURCE.lowranceKayak,
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "buyer_question",
    content: "Real setup question: what tablet mount works on a forklift overhead guard, cage, pillar, or roll bar without blocking the operator's view?",
    sourceUrl: SOURCE.iboltForklift,
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "buyer_question",
    content: "Real setup question: how do I keep a barcode scanner from bouncing around or getting dropped when the forklift operator needs to scan pallets all shift?",
    sourceUrl: SOURCE.zebraForkliftScanning,
  },
  {
    verticalSlug: "forklifts-warehousing",
    category: "buyer_question",
    content: "Real setup question: do I need a 38mm C-size ball mount for a forklift tablet, or is a smaller 25mm ball enough?",
    sourceUrl: SOURCE.iboltForklift,
  },
  {
    verticalSlug: "trucking-fleet",
    category: "buyer_question",
    content: "Real setup question: where can I mount an ELD tablet so it is fixed, visible from the normal seated driving position, and not blocking the windshield?",
    sourceUrl: SOURCE.fmcsaEld,
  },
  {
    verticalSlug: "trucking-fleet",
    category: "buyer_question",
    content: "Real setup question: what no-drill mount works in a company truck when I cannot screw into the dash?",
    sourceUrl: SOURCE.iboltFleet,
  },
  {
    verticalSlug: "trucking-fleet",
    category: "buyer_question",
    content: "Real setup question: how do I mount both a phone and an ELD tablet without crowding the dashboard or creating cable clutter?",
    sourceUrl: SOURCE.iboltFleet,
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "buyer_question",
    content: "Real setup question: how do I organize DoorDash, Uber Eats, Grubhub, and POS tablets so staff can see every order during rush?",
    sourceUrl: SOURCE.doorDashTablet,
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "buyer_question",
    content: "Real setup question: should a restaurant use a wall mount, clamp mount, drill-base stand, or weighted stand for delivery app tablets?",
    sourceUrl: SOURCE.iboltPos,
  },
  {
    verticalSlug: "restaurants-food-delivery",
    category: "buyer_question",
    content: "Real setup question: what locking tablet stand should I use for a customer-facing POS or self-service station?",
    sourceUrl: SOURCE.squareStand,
  },
  {
    verticalSlug: "offroading-jeep",
    category: "buyer_question",
    content: "Real setup question: what phone or tablet mount will stay put on washboard roads, rock crawling trails, and UTV roll cages?",
    sourceUrl: SOURCE.iboltOffroad,
  },
  {
    verticalSlug: "offroading-jeep",
    category: "buyer_question",
    content: "Real setup question: what clamp size do I need for a UTV roll bar, and how do I measure the tube before buying?",
    sourceUrl: SOURCE.iboltOffroad,
  },
  {
    verticalSlug: "offroading-jeep",
    category: "buyer_question",
    content: "Real setup question: should I use a phone, tablet, Garmin Tread, or action camera for trail navigation and filming?",
    sourceUrl: SOURCE.garminTread,
  },
  {
    verticalSlug: "education-schools",
    category: "buyer_question",
    content: "Real setup question: does a school bus tablet mount need to be removable, locked, or able to go dark while the bus is moving?",
    sourceUrl: SOURCE.zonarSchoolBus,
  },
  {
    verticalSlug: "education-schools",
    category: "buyer_question",
    content: "Real setup question: what locking tablet stand works for a shared classroom, library, check-in desk, or student station?",
    sourceUrl: SOURCE.iboltEducation,
  },
  {
    verticalSlug: "education-schools",
    category: "buyer_question",
    content: "Real setup question: can I use an iPad or phone as a document camera over worksheets, books, or demonstrations?",
    sourceUrl: SOURCE.teachersReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "content-creation-streaming",
    category: "buyer_question",
    content: "Real setup question: what is the best phone stand for TikTok Live, YouTube Shorts, product demos, or live selling from a desk?",
    sourceUrl: SOURCE.iboltStreaming,
  },
  {
    verticalSlug: "content-creation-streaming",
    category: "buyer_question",
    content: "Real setup question: can the same mount hold a phone, small camera, light, mic, and tablet monitor with 1/4-20 adapters?",
    sourceUrl: SOURCE.videographyReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "content-creation-streaming",
    category: "buyer_question",
    content: "Real setup question: how do I stop an overhead camera mount from shaking every time I touch the desk or counter?",
    sourceUrl: SOURCE.videographyReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "agriculture-farming",
    category: "buyer_question",
    content: "Real setup question: will suction work on curved tractor cab glass, or do I need a drill base, clamp mount, or monitor-rail setup?",
    sourceUrl: SOURCE.newAgTalkIpad,
  },
  {
    verticalSlug: "agriculture-farming",
    category: "buyer_question",
    content: "Real setup question: can I move the same tablet mount between a tractor, sprayer, combine, and farm UTV?",
    sourceUrl: SOURCE.iboltAgriculture,
  },
  {
    verticalSlug: "agriculture-farming",
    category: "buyer_question",
    content: "Real setup question: what mount holds a 12-inch iPad Pro or Samsung Tab Active in a tractor cab without bouncing in rough fields?",
    sourceUrl: SOURCE.iboltTractor,
  },
  {
    verticalSlug: "kitchen-home",
    category: "buyer_question",
    content: "Real setup question: how do I mount an iPad under a kitchen cabinet and still hide it or fold it away when not in use?",
    sourceUrl: SOURCE.iboltKitchen,
  },
  {
    verticalSlug: "kitchen-home",
    category: "buyer_question",
    content: "Real setup question: can I mount a tablet on the refrigerator with magnets, and how much weight can the magnetic mount hold?",
    sourceUrl: SOURCE.iboltMagDock,
  },
  {
    verticalSlug: "kitchen-home",
    category: "buyer_question",
    content: "Real setup question: how do I power a wall-mounted kitchen or smart-home dashboard tablet without visible cables?",
    sourceUrl: SOURCE.smartHomeReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "road-trips-travel",
    category: "buyer_question",
    content: "Real setup question: will a headrest tablet mount fit a bulky kid-proof tablet case and still leave the charging port open?",
    sourceUrl: SOURCE.iboltRoadTrip,
  },
  {
    verticalSlug: "road-trips-travel",
    category: "buyer_question",
    content: "Real setup question: what removable no-drill tablet mount works in an RV, van, rental car, or passenger seat?",
    sourceUrl: SOURCE.iboltHeadrest,
  },
  {
    verticalSlug: "road-trips-travel",
    category: "buyer_question",
    content: "Real setup question: are suction, vent, CD-slot, cup-holder, or headrest mounts better for long road trips with tablets?",
    sourceUrl: SOURCE.roadTripReddit,
    sourceType: "reddit",
  },
  {
    verticalSlug: "mountain-biking-cycling",
    category: "buyer_question",
    content: "Real setup question: what phone mount stays secure on mountain bike trails without damaging the phone camera?",
    sourceUrl: SOURCE.appleVibration,
  },
  {
    verticalSlug: "mountain-biking-cycling",
    category: "buyer_question",
    content: "Real setup question: should I use Trailforks on my phone, a Garmin Edge, or a Wahoo for trail and bikepacking navigation?",
    sourceUrl: SOURCE.trailforks,
  },
  {
    verticalSlug: "mountain-biking-cycling",
    category: "buyer_question",
    content: "Real setup question: what handlebar clamp or stem mount works with gloves, rain, mud, brake cables, and quick phone removal?",
    sourceUrl: SOURCE.iboltCycling,
  },
  {
    verticalSlug: "general-mounting",
    category: "buyer_question",
    content: "Real setup question: what is the ball socket called if I want a low-profile plate instead of a big articulated arm?",
    sourceUrl: "https://www.reddit.com/r/peakdesign/comments/1m0eowi/20mm1in_ball_mount_sockets/",
    sourceType: "reddit",
  },
  {
    verticalSlug: "general-mounting",
    category: "buyer_question",
    content: "Real setup question: do AMPS holes always line up, or do I need to check 2-hole versus 4-hole spacing and orientation before drilling?",
    sourceUrl: SOURCE.ampsExplainer,
  },
  {
    verticalSlug: "general-mounting",
    category: "buyer_question",
    content: "Real setup question: can an AAC tablet or wheelchair-mounted device stay mounted during school bus or van transport?",
    sourceUrl: "https://www.reddit.com/r/slp/comments/1our1lm/parent_question_here_has_anyone_heard_of_a/",
    sourceType: "reddit",
  },
] satisfies ContextEnrichmentEntry[];

export const CONTEXT_ENRICHMENT_SOURCE_URLS_2026_06_22 = Object.values(SOURCE);
