#!/usr/bin/env node
// verify-plan.mjs — completion verifier for CODEX-IMPLEMENTATION-PLAN.md
//
// Usage:
//   node scripts/verify-plan.mjs            full run (static checks + typecheck + tests)
//   node scripts/verify-plan.mjs --static   static checks only (fast iteration)
//
// Exit code 0 = the implementation plan is complete. Non-zero = work remains.
// DO NOT EDIT THIS FILE TO MAKE CHECKS PASS. Implement the plan instead.

import { readFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const STATIC_ONLY = process.argv.includes("--static");

const results = [];

function read(rel) {
  try {
    return readFileSync(path.join(ROOT, rel), "utf8");
  } catch {
    return null;
  }
}

function check(task, name, pass, hint = "") {
  results.push({ task, name, pass: Boolean(pass), hint });
}

function contains(rel, pattern) {
  const content = read(rel);
  if (content === null) return false;
  return pattern instanceof RegExp ? pattern.test(content) : content.includes(pattern);
}

function fileExists(rel) {
  return existsSync(path.join(ROOT, rel));
}

// ---------------------------------------------------------------------------
// T1 — Pipeline bug fixes
// ---------------------------------------------------------------------------
{
  const pipeline = read("server/blogPipeline.ts") || "";
  const anthropicCallBody = pipeline.split("anthropic.messages.create({")[1]?.split("});")[0] ?? "";
  check("T1", "temperature passed to Anthropic in generateText", anthropicCallBody.includes("temperature"),
    "server/blogPipeline.ts: add temperature to the anthropic.messages.create call");
  check("T1", "fishing-bias scoring line removed", !/fish\|marine\|boat\|kayak/.test(pipeline),
    "server/blogPipeline.ts: delete the /fish|marine|boat|kayak/ score boost in getClusterData");
  check("T1", "blog_posts has generation_provider column", contains("shared/schema.ts", "generation_provider"),
    "shared/schema.ts: add generationProvider to blogPosts");
  check("T1", "blog_posts has generation_model column", contains("shared/schema.ts", "generation_model"),
    "shared/schema.ts: add generationModel to blogPosts");
}

// ---------------------------------------------------------------------------
// T2 — Content linter
// ---------------------------------------------------------------------------
check("T2", "server/contentLinter.ts exists", fileExists("server/contentLinter.ts"));
check("T2", "lintContent is exported", contains("server/contentLinter.ts", /export function lintContent/));
check("T2", "linter imports BRAND_VOICE (no copied lists)", contains("server/contentLinter.ts", /from ["']\.\/brandVoice["']/),
  "import the banned-phrase list from brandVoice.ts, do not duplicate it");
check("T2", "pipeline integrates linter", contains("server/blogPipeline.ts", "lintContent"),
  "run lintContent after stitching in runBlogPipeline");
check("T2", "lint API route exists", contains("server/blogRoutes.ts", "/lint"),
  "POST /api/blog/lint in server/blogRoutes.ts");
check("T2", "lint_content MCP tool registered", contains("mcp-server/ibolt-stdio.mjs", '"lint_content"'));
check("T2", "tests/contentLinter.test.ts exists", fileExists("tests/contentLinter.test.ts"));

// ---------------------------------------------------------------------------
// T3 — Grounded verifier + quality gate
// ---------------------------------------------------------------------------
check("T3", "buildVerifierPrompt accepts product facts", contains("server/brandVoice.ts", "productFacts"),
  "server/brandVoice.ts: buildVerifierPrompt(productFacts) with a Product Catalog Facts section");
check("T3", "quality gate is env-configurable (BLOG_QUALITY_GATE)", contains("server/blogPipeline.ts", "BLOG_QUALITY_GATE"));
check("T3", "no hardcoded >= 70 gate remains", !contains("server/blogPipeline.ts", ">= 70"),
  "replace the hardcoded 70 threshold");

// ---------------------------------------------------------------------------
// T4 — Research expansion
// ---------------------------------------------------------------------------
check("T4", "schema: research_subreddits column", contains("shared/schema.ts", "research_subreddits"));
check("T4", "schema: research_youtube_queries column", contains("shared/schema.ts", "research_youtube_queries"));
check("T4", "schema: research_web_queries column", contains("shared/schema.ts", "research_web_queries"));
check("T4", "schema: last_researched_at column", contains("shared/schema.ts", "last_researched_at"));
check("T4", "scheduler: maxVerticalsPerResearchRun config", contains("server/scheduler.ts", "maxVerticalsPerResearchRun"));
check("T4", "scheduler: default research sources include reddit+youtube+web",
  contains("server/scheduler.ts", /researchSources:\s*\[\s*["']reddit["']\s*,\s*["']youtube["']\s*,\s*["']web["']\s*\]/),
  "DEFAULT_CONFIG.researchSources must be all three sources");
check("T4", "scheduler: research interval default is 6h",
  contains("server/scheduler.ts", /researchIntervalMs:\s*6\s*\*\s*60\s*\*\s*60\s*\*\s*1000/),
  "DEFAULT_CONFIG.researchIntervalMs = 6 * 60 * 60 * 1000");
check("T4", "getResearchCoverage implemented",
  contains("server/iboltResearchAgent.ts", "getResearchCoverage") || contains("server/researchCoverage.ts", "getResearchCoverage"));
check("T4", "suggestMissingVerticals implemented", contains("server/verticalCreator.ts", "suggestMissingVerticals"));
check("T4", "vertical creator generates research sources", contains("server/verticalCreator.ts", "researchSubreddits"),
  "createVerticalFromDescription must request and store research sources");
check("T4", "coverage API route exists",
  contains("server/blogRoutes.ts", "research/coverage") || contains("server/contextRoutes.ts", "research/coverage"));
check("T4", "get_research_coverage MCP tool", contains("mcp-server/ibolt-stdio.mjs", '"get_research_coverage"'));
check("T4", "suggest_verticals MCP tool", contains("mcp-server/ibolt-stdio.mjs", '"suggest_verticals"'));
check("T4", "create_vertical MCP tool", contains("mcp-server/ibolt-stdio.mjs", '"create_vertical"'));
check("T4", "tests/researchCoverage.test.ts exists", fileExists("tests/researchCoverage.test.ts"));

// ---------------------------------------------------------------------------
// T5 — Internal linking
// ---------------------------------------------------------------------------
check("T5", "server/internalLinker.ts exists", fileExists("server/internalLinker.ts"));
check("T5", "addInternalLinks exported", contains("server/internalLinker.ts", /export async function addInternalLinks/));
check("T5", "pipeline calls addInternalLinks", contains("server/blogPipeline.ts", "addInternalLinks"));
check("T5", "internal-links API route exists", contains("server/blogRoutes.ts", "internal-links"));
check("T5", "add_internal_links MCP tool", contains("mcp-server/ibolt-stdio.mjs", '"add_internal_links"'));
check("T5", "tests/internalLinker.test.ts exists", fileExists("tests/internalLinker.test.ts"));

// ---------------------------------------------------------------------------
// T6 — Rendering + structured data
// ---------------------------------------------------------------------------
{
  const pkg = JSON.parse(read("package.json") || "{}");
  const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
  check("T6", "marked dependency added", Boolean(deps["marked"]));
  check("T6", "htmlRenderer uses marked", contains("server/htmlRenderer.ts", /from ["']marked["']/));
  check("T6", "Article JSON-LD emitted", contains("server/htmlRenderer.ts", '"Article"'));
  check("T6", "BreadcrumbList JSON-LD emitted", contains("server/htmlRenderer.ts", '"BreadcrumbList"'));
  check("T6", "ItemList JSON-LD emitted for listicles", contains("server/htmlRenderer.ts", '"ItemList"'));
  check("T6", "tests/htmlRenderer.test.ts exists", fileExists("tests/htmlRenderer.test.ts"));
}

// ---------------------------------------------------------------------------
// T7 — Benchmark MCP tools
// ---------------------------------------------------------------------------
for (const tool of [
  "run_ai_benchmark",
  "get_benchmark_summary",
  "list_benchmark_queries",
  "add_benchmark_query",
  "generate_content_plan",
  "materialize_content_plan",
]) {
  check("T7", `${tool} MCP tool registered`, contains("mcp-server/ibolt-stdio.mjs", `"${tool}"`));
}

// ---------------------------------------------------------------------------
// T8 — Content refresh
// ---------------------------------------------------------------------------
check("T8", "scheduler has runContentRefresh", contains("server/scheduler.ts", "runContentRefresh"));
check("T8", "scheduler has autoRefresh config (default false)", contains("server/scheduler.ts", /autoRefresh:\s*false/));
check("T8", "manual refresh route exists", contains("server/blogRoutes.ts", "/refresh"));
check("T8", "refresh_post MCP tool", contains("mcp-server/ibolt-stdio.mjs", '"refresh_post"'));

// ---------------------------------------------------------------------------
// T9 — Hygiene
// ---------------------------------------------------------------------------
{
  const envExample = read(".env.example") || "";
  const requiredVars = ["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "SHOPIFY_CLIENT_ID", "SHOPIFY_CLIENT_SECRET", "PUBLIC_BASE_URL", "BLOG_QUALITY_GATE"];
  check("T9", ".env.example exists with required vars", requiredVars.every((v) => envExample.includes(v)),
    `must include: ${requiredVars.join(", ")}`);
  const pkg = JSON.parse(read("package.json") || "{}");
  const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
  check("T9", "papaparse dependency added", Boolean(deps["papaparse"]));
  check("T9", "keywordManager uses papaparse", contains("server/keywordManager.ts", /from ["']papaparse["']|require\(["']papaparse["']\)/));
  check("T9", "tests/keywordManager.test.ts exists", fileExists("tests/keywordManager.test.ts"));
  check("T9", "clustering is chunked", contains("server/keywordManager.ts", /150|chunk/i),
    "clusterKeywords must batch keywords (150 per LLM call)");
}

// ---------------------------------------------------------------------------
// Build + tests (skipped with --static)
// ---------------------------------------------------------------------------
const NEW_TEST_FILES = [
  "tests/contentLinter.test.ts",
  "tests/htmlRenderer.test.ts",
  "tests/internalLinker.test.ts",
  "tests/keywordManager.test.ts",
  "tests/researchCoverage.test.ts",
];

if (!STATIC_ONLY) {
  if (!fileExists("node_modules")) {
    check("BUILD", "node_modules installed", false, "run: npm install");
  } else {
    try {
      execSync("npm run check", { cwd: ROOT, stdio: "pipe", timeout: 300000 });
      check("BUILD", "npm run check (TypeScript)", true);
    } catch (err) {
      const out = `${err.stdout || ""}${err.stderr || ""}`.split("\n").slice(-15).join("\n");
      check("BUILD", "npm run check (TypeScript)", false, out.trim());
    }

    const existingTests = NEW_TEST_FILES.filter((f) => fileExists(f));
    if (existingTests.length === 0) {
      check("TESTS", "new test files present", false, "no plan test files exist yet");
    } else {
      try {
        execSync(`npx vitest run ${existingTests.join(" ")}`, { cwd: ROOT, stdio: "pipe", timeout: 300000 });
        check("TESTS", `vitest (${existingTests.length}/${NEW_TEST_FILES.length} plan test files)`, existingTests.length === NEW_TEST_FILES.length,
          existingTests.length === NEW_TEST_FILES.length ? "" : "some plan test files are missing");
      } catch (err) {
        const out = `${err.stdout || ""}${err.stderr || ""}`.split("\n").slice(-20).join("\n");
        check("TESTS", "vitest on plan test files", false, out.trim());
      }
    }
  }
} else {
  console.log("(--static: skipping typecheck and tests; final completion requires a full run)\n");
}

// ---------------------------------------------------------------------------
// Report
// ---------------------------------------------------------------------------
const byTask = new Map();
for (const r of results) {
  if (!byTask.has(r.task)) byTask.set(r.task, []);
  byTask.get(r.task).push(r);
}

let failed = 0;
for (const [task, items] of byTask) {
  const taskFails = items.filter((i) => !i.pass);
  const icon = taskFails.length === 0 ? "DONE" : "TODO";
  console.log(`[${icon}] ${task} — ${items.length - taskFails.length}/${items.length} checks passing`);
  for (const item of items) {
    if (!item.pass) {
      console.log(`    FAIL: ${item.name}`);
      if (item.hint) console.log(`          hint: ${item.hint.split("\n").join("\n          ")}`);
      failed++;
    }
  }
}

console.log(`\n${results.length - failed}/${results.length} checks passing.`);
if (failed === 0) {
  console.log("PLAN COMPLETE. All verification checks pass.");
  process.exit(0);
} else {
  console.log(`${failed} checks remaining. Work through tasks in order (T1 -> T9), then re-run.`);
  process.exit(1);
}
